### ISSUE TITLE
add live sidebar

### ISSUE THREAD

**Issue by wen-jams** [wen-jams/bsavi#3]
- updates with values of other params on mouse hover

**Comment by wen-jams** [comment]
initial version of this is linking the plot and a table together using `link_selections()`
![image](https://user-images.githubusercontent.com/40677090/188556801-855ae147-ad10-483f-b08c-a12c9fc8b449.png)

**Comment by maamari** [comment]
Nice work here, didn't know you could add a table like that. Looks really good. I see what you're saying about wanting the table to collapse to only the selected entries. I also don't expect this to be trivial. 

I don't see any parameter in the Table documentation that allows you to simply collapse the table, so I think your best bet is trying some sort of 
`selection = streams.Selection1D(source=scat)`
After producing the scatter but before producing the table. When you make a selection on the scatter plot, `selection` will be filled with the indices of the selected points. You can index slice the dataframe then with iloc and produce the table accordingly.

There are a bunch of problems associated with this though. For one, I don't know if you can link the plots with the table if you do this because they'll be of different size. Also, you'd have to figure out a way to manually refresh the plot every time you make a selection on the scatter but before you create the table -- I expect this will be both computational expensive and difficult to implement. If you can pull it off you'd be a legend, but you might be better off looking for a different solution.

That all being said, it doesn't look bad as is by any stretch, but I do agree that a table of selected entries only would look better. Since you have a decent solution already, I might stick this as a last priority. Might swallow up all your time otherwise

**Comment by wen-jams** [comment]
this approach worked!
